version: '3.8'

services:
  app:
    # build: .
    image: ghcr.io/nuntawatt/adenxus-demo-nest:latest
    container_name: adenxus-demo-nest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # Add other environment variables as needed
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     container_name: adenxus-db
#     restart: always
#     environment:
#       POSTGRES_USER: nestuser
#       POSTGRES_PASSWORD: nestpassword
#       POSTGRES_DB: nestdb
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data: